console.log("    _/    _/            _/                      ")
console.log("   _/    _/    _/_/_/      _/_/_/      _/_/_/   ")
console.log("  _/_/_/_/  _/_/      _/  _/    _/  _/    _/    ")
console.log(" _/    _/      _/_/  _/  _/    _/  _/    _/     ")
console.log("_/    _/  _/_/_/    _/  _/    _/    _/_/_/      ")
console.log("                                       _/       ")
console.log("                                  _/_/          ")